const fieldConfig = {
  "Leads Expert": {
    "ACA CPL": ["phone", "zipcode", "exposeCallerId", "state", "agentName"],
    "HI-Xfers-windows": ["phone", "zipcode", "exposeCallerId", "state", "agentName"],
    "ACA CPA": ["phone", "zipcode", "exposeCallerId", "state", "agentName"],
    "ACA Rev Share": ["phone", "zipcode", "exposeCallerId", "agentName", "Age"],
    "ACA Scrub": ["phone", "zipcode", "exposeCallerId", "agentName", "Age"],
    "FE CPL/xfers": [
      "phone",
      "zipcode",
      "state",
      "exposeCallerId",
      "agentName",
      "jornaya_leadid",
      "Age",
    ],
    "FE FDNC": [
      "phone",
      "zipcode",
      "state",
      "exposeCallerId",
      "agentName",
      "jornaya_leadid",
      "Age",
    ],
    "Medicare CPL": ["phone", "zipcode", "exposeCallerId", "agentName", "Age"],
    "ACA-Xfers-CPA": ["callerid", "exposeCallerId", "ZipCode", "state", "Age"],
    "U65-Xfers-20K-PH": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "state",
      "agentName",
      "firstname",
      "lastname",
      "email",
    ],
    "Medicare-CPA-Xfers": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "state",
      "agentName",
      "firstname",
      "lastname",
    ],
    "ACA-Xfers-CPL": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "state",
      "agentName",
      "firstname",
      "lastname",
      "jornaya_leadid",
      "trusted_id",
    ],
    "Medicare Warm xfers": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "state",
      "jornaya_leadid",
    ],
  },
  WWWIST: {
    "ACA-Xfers-CPL": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
      "trusted_id",
    ],
    "ACA-Xfers-CPL-Scrub": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
      "trusted_id",
    ],
    "ACA-Xfers-RevShare": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
      "trusted_id",
    ],
    "ACA-Xfers-RevShare-Scrub": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
      "trusted_id",
    ],
    "ACA-Xfers-CPA": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
      "trusted_id",
    ],
  },
  BaliTech: {
    "ACA CPL": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "firstname",
      "lastname",
      "address",
      "city",
      "state",
      "dob",
      "email",
      "Age",
      "agentName",
    ],
    "ACA Rev Share": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
    ],
    "ACA Scrub": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "jornaya_leadid",
    ],
    "ACA CPA": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "jornaya_leadid",
    ],
    "Medicare CPL": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
    ],
    "Broadband-Xfers-CPA": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "jornaya_leadid",
    ],
    "ACA-Xfers-CPL-Scrub": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "state",
    ],
    "ACA-Xfers-CPL-TB-Boss": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
    ],
    "FE-Xfers": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
      "Age",
    ],
    "ACA-Xfers-CPA": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "state",
      "agentName",
    ],
    "SSDI-CPL": [
      "phone",
      "exposeCallerId",
      "Age",
      "agentName",
    ],
    "U65-Xfers-20K-PH": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "state",
      "agentName",
      "firstname",
      "lastname",
      "email",
    ],
  },
  adolicius: {
    RevShare: [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "firstname",
      "lastname",
      "email",
      "city",
      "state",
      "address",
    ],
  },
  ProVoice: {
    "AUTO-Xfers": ["phone", "exposeCallerId", "ZipCode", "dob", "state"],
  },
  "Maximize Reach": {
    "ACA CPL": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "firstname",
      "lastname",
      "address",
      "city",
      "state",
      "dob",
      "email",
      "jornaya_leadid",
      "ip_address",
      "Age",
    ],
    "ACA-CPA": ["phone", "ZipCode", "exposeCallerId", "state", "agentname"],
    "ACA-Xfers-RevShare": ["phone", "ZipCode", "exposeCallerId", "agentname"],
    "SSDI-CPA-Xfers ONSHORE": [
      "phone",
      "ZipCode",
      "exposeCallerId",
      "agentname",
      "state",
      "Age",
    ],
    "SSDI-Xfers-CPA": [
      "phone",
      "ZipCode",
      "exposeCallerId",
      "agentname",
      "state",
      "Age",
    ],
    "ACA-Xfers-CPL-Scrub": [
      "phone",
      "ZipCode",
      "exposeCallerId",
      "agentname",
      "state",
    ],
  },
  BMI: {
    "ACA-Xfers-CPL": [
      "phone",
      "ZipCode",
      "exposeCallerId",
      "lname",
      "address",
      "agentName",

      "Age",
    ],
    "FE FDNC": [
      "phone",
      "zipcode",
      "state",
      "exposeCallerId",
      "agentName",
      "jornaya_leadid",
      "Age",
    ],
    "FE-Xfers": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "state",
      "agentName",
      "jornaya_leadid",
      "Age",
    ],
    "Auto-Xfers": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "state",
      "dob",
      "jornaya_leadid",
      "agentName",
    ],
    "ACA-Xfers-RevShare": ["phone", "exposeCallerId", "zipcode", "agentName"],
    "SSDI CPA": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "agentName",
      "state",
      "Age",
    ],
  },
  "Golden Spruce": {
    "ACA Rev Share": ["phone", "zipcode", "exposeCallerId", "agentName"],
    "ACA CPL": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "firstname",
      "lastname",
      "address",
      "city",
      "state",
      "dob",
      "email",
      "jornaya_leadid",
      "ip_address",
      "Age",
      "agentName",
    ],
    "FE-Xfers": ["phone", "zipcode", "exposeCallerId", "agentName", "Age"],
  },
  Assured: {
    "ACA-Revshare": ["phone", "zipcode", "exposeCallerId", "agentName"],
    "SSDI-CPA": ["phone", "exposeCallerId", "agentName", "Age", "zipcode"],
    "SSDI-CPL": ["phone", "exposeCallerId", "agentName", "Age", "zipcode"],
    "ACA-CPL": ["phone", "exposeCallerId", "agentName", "zipcode", "state"],
    "HI-Xfers-Window": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "jornaya_leadid",
      "trusted_id",
      "agentName",
      "firstname",
      "lastname",
      "address",
      "city",
      "state",
      "dob",
      "email",
      "ip_address",
    ],
  },
  "Workerz LLC": {
    "ACA-CPA": [
      "phone",
      "zipcode",
      "exposeCallerId",
      "agentName",
      "jornaya_leadid",
      "state",
    ],
    "ACA-CPL": ["phone", "zipcode", "exposeCallerId", "agentName", "state"],
    "ACA-Revshare": ["phone", "zipcode", "exposeCallerId", "agentName"],
  },
  "Camiz Global": {
    "SSDI CPL": ["phone", "exposeCallerId", "agentName", "Age"],
    "SSDI-CPA": ["phone", "zipcode", "exposeCallerId", "agentName", "Age"],
    "MVA-Xfers": [
      "phone",
      "exposeCallerId",
      "zipcode",
      "agentName",
      "firstname",
      "lastname",
      "address",
      "city",
      "state",
      "dob",
      "email",
      "ip_address",
      "Age",
      "trusted_id",
      "jornaya_leadid",
      "Incident_date",
      "accident_state",
      "injured",
      "injury",
      "source_url",
    ],
  },
  RNT: {
    "Medicare-Xfers-Cpl": [
      "phone",
      "exposeCallerId",
      "agentName",
      "zipcode",
      "state",
    ],
    "FE-Xfers": [
      "phone",
      "exposeCallerId",
      "agentName",
      "zipcode",
      "state",
      "firstname",
      "lastname",
      "address",
      "city",
      "state",
      "dob",
      "email",
      "jornaya_leadid",
      "ip_address",
      "trusted_id",
      "Age",
    ],
  },
};

module.exports = fieldConfig;
