export const campaignRelations = {
  "Leads Expert": [
    "ACA CPL",
    "ACA CPA",
    "ACA Rev Share",
    "ACA Scrub",
    "FE CPL/xfers",
    "FE FDNC",
    "Medicare CPL",
    "ACA-Xfers-CPA",
    "SSDI-CPA",
    "MVA Transfers",
    "U65-Xfers-20K-PH",
    "Medicare-CPA-Xfers",
    "ACA-Xfers-CPL",
    "Medicare Warm xfers",
    "HI-Xfers-windows" 
  ],
  "WWWIST": [
    "ACA-Xfers-CPL",
    "ACA-Xfers-CPL-Scrub",
    "ACA-Xfers-RevShare",
    "ACA-Xfers-RevShare-Scrub",
    "ACA-Xfers-CPA",
  ],
  BaliTech: [
    "ACA CPL",
    "ACA Rev Share",
    "ACA Scrub",
    "ACA CPA",
    "Medicare CPL",
    "Broadband-Xfers-CPA",
    "SSDI-CPL",
    "ACA-Xfers-CPL-TB-Boss",
    "FE-Xfers",
    "ACA-Xfers-CPA",
    "U65-Xfers-20K-PH",
  ],
  adolicius: ["RevShare"],
  ProVoice: ["AUTO-Xfers"],
  "Maximize Reach": ["ACA-CPL", "ACA-CPA", "ACA-Xfers-RevShare","SSDI-CPA-Xfers ONSHORE","ACA-Xfers-CPL-Scrub","SSDI-Xfers-CPA"],
  BMI: [
    // "ACA-Xfers-CPL",
    // "Auto-Xfers",
    // "ACA-Xfers-RevShare",
    // "ACA-Xfers-CPA",
    // "ACA-Xfers-CPL-Scrub",
    "FE-Xfers",
    // "FE FDNC",
    "SSDI CPA"
  ],
  "1st Choice": ["SSDI-CPL"],
  "Golden Spruce": ["ACA Rev Share", "ACA CPL", "FE-Xfers"],
  Assured: [
    "SSDI-CPA",
    "SSDI-CPL",
    "ACA-Revshare",
    "HI-Xfers-Window",
    "ACA-CPL",
  ],
  "Workerz LLC": ["ACA-CPA", "ACA-CPL", "ACA-Revshare"],
  "Camiz Global": ["SSDI CPL", "MVA-Xfers","SSDI-CPA"],
  RNT: ["Medicare-Xfers-Cpl","FE-Xfers"],
};
